### ISSUE TITLE
Ticking entity crash from chicken

### ISSUE THREAD

**Issue by sixtymillionsqrd** [SaemonMoki/ExtendedAnimals#32]
Seems to be a conflict with Charm?

---- Minecraft Crash Report ----
// My bad.

Time: 5/1/20 9:27 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at mokiyoki.enhancedanimals.loot.EnhancedChickenLootCondition.test(EnhancedChickenLootCondition.java:21) ~[?:0.4.11] {re:classloading}
	at mokiyoki.enhancedanimals.loot.EnhancedChickenLootCondition.test(EnhancedChickenLootCondition.java:16) ~[?:0.4.11] {re:classloading}
	at net.minecraft.world.storage.loot.LootPool.func_216091_a(LootPool.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.storage.loot.LootTable.func_216114_a(LootTable.java:70) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.storage.loot.LootTable.func_216120_b(LootTable.java:82) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.storage.loot.LootTable.func_216113_a(LootTable.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_213354_a(LivingEntity.java:1173) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity}
	at net.minecraft.entity.MobEntity.func_213354_a(MobEntity.java:426) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_213345_d(LivingEntity.java:1147) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity}
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntity.java:1115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:973) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity}
	at net.minecraft.entity.passive.AnimalEntity.func_70097_a(SourceFile:67) ~[?:?] {re:classloading}
	at its_meow.betteranimalsplus.common.entity.EntityBoar.func_70652_k(EntityBoar.java:147) ~[?:9.0.1] {re:classloading}
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_190102_a(MeleeAttackGoal.java:138) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:130) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$8837/1007718626.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:80) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:590) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2187) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:140) ~[?:?] {re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2033) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:charm:LivingEntity}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.world.server.ServerWorld$$Lambda$8816/1760718766.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mokiyoki.enhancedanimals.loot.EnhancedChickenLootCondition.test(EnhancedChickenLootCondition.java:21)
	at mokiyoki.enhancedanimals.loot.EnhancedChickenLootCondition.test(EnhancedChickenLootCondition.java:16)
	at net.minecraft.world.storage.loot.LootPool.func_216091_a(LootPool.java:87)
	at net.minecraft.world.storage.loot.LootTable.func_216114_a(LootTable.java:70)
	at net.minecraft.world.storage.loot.LootTable.func_216120_b(LootTable.java:82)
	at net.minecraft.world.storage.loot.LootTable.func_216113_a(LootTable.java:87)
	at net.minecraft.entity.LivingEntity.func_213354_a(LivingEntity.java:1173)
	at net.minecraft.entity.MobEntity.func_213354_a(MobEntity.java:426)
	at net.minecraft.entity.LivingEntity.func_213345_d(LivingEntity.java:1147)
	at net.minecraft.entity.LivingEntity.func_70645_a(LivingEntity.java:1115)
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:973)
	at net.minecraft.entity.passive.AnimalEntity.func_70097_a(SourceFile:67)
	at its_meow.betteranimalsplus.common.entity.EntityBoar.func_70652_k(EntityBoar.java:147)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_190102_a(MeleeAttackGoal.java:138)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:130)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$8837/1007718626.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:80)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:590)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2187)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460)
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:140)
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2033)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)
	at net.minecraft.world.server.ServerWorld$$Lambda$8816/1760718766.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: betteranimalsplus:boar (its_meow.betteranimalsplus.common.entity.EntityBoar)
	Entity ID: 12
	Entity Name: Boar
	Entity's Exact location: -252.40, 64.00, -35.59
	Entity's Block location: World: (-253,64,-36), Chunk: (at 3,4,12 in -16,-3; contains blocks -256,0,-48 to -241,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: -0.18, -0.08, -0.11
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['SixtyMillionSqrd'/276, l='New World', x=-91.94, y=128.00, z=-17.90]]
	Chunk stats: ServerChunkCache: 2409
	Level dimension: DimensionType{minecraft:overworld}
	Level name: New World
	Level seed: -2963301531816368860
	Level generator: ID 07 - wildnature, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-208,75,0), Chunk: (at 0,4,0 in -13,0; contains blocks -208,0,0 to -193,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 617 game time, 617 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 61925 (now: false), thunder time: 89995 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:766)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 819994696 bytes (782 MB) / 3796893696 bytes (3621 MB) up to 7492075520 bytes (7145 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8037m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.6.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.6.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.6.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.6.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.6.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.6
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.6-client.jar Minecraft {minecraft@1.14.4 DONE}
		lizardmod-1.14.4-1.0.0-1.jar Lizard Mod {lizardmod@1.14.4-1.0.0-1 DONE}
		turtlemod-1.14.4-1.1.0-3.jar Turtle Mod {turtlemod@1.14.4-1.1.0-3 DONE}
		crocmod-1.14.4-1.0.0-1.jar Crocodile Mod {crocmod@1.14.4-1.0.0-1 DONE}
		pandoras_creatures-1.14.4-0.12.0.jar Pandoras Creatures {pandoras_creatures@1.14.4-0.12.0 DONE}
		pamhc2trees-1.14.4-1.0.0.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		pamhc2crops-1.14.4-1.0.4.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		seafaring-1.14.4-0.2.2.jar Seafaring {sea@0.2.2 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		Druidcraft-1.14-0.3.1.jar Druidcraft {druidcraft@0.3.1 DONE}
		GeneticAnimals_0_4_13.jar Genetic Animals {eanimod@0.4.11 DONE}
		wildnature-2.1.6.5.jar WildNature {wildnature@2.1.6.5 DONE}
		Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		whisperwoods-1.14.4-1.0.1.jar Whisperwoods {whisperwoods@1.0.1 DONE}
		Patchouli-1.14.4-1.1-26.5.jar Patchouli {patchouli@1.14.4-1.1-27 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		pamhc2foodcore-1.14.4-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		autumnity-1.0.0-1.14.4.jar Autumnity {autumnity@1.0.0 DONE}
		horse_colors-1.14.4-1.1.0.jar Realistic Horse Genetics {horse_colors@1.14.4-1.1.0 DONE}
		citadel-1.0.4-1.14.4.jar Citadel {citadel@1.0.4 DONE}
		rats-4.1.1-1.14.4.jar Rats {rats@4.1.1 DONE}
		good-nights-sleep-1.14.4-1.0.3.jar Good Night's Sleep {goodnightsleep@1.0.3 DONE}
		betteranimalsplus-1.14.4-9.0.1.jar Better Animals Plus {betteranimalsplus@9.0.1 DONE}
		Waddles-1.14.4-0.8.3.jar Waddles {waddles@1.14.4-0.8.3 DONE}
		voyage-1.0.0.jar Voyage {voyage@1.0.0 DONE}
		EnhancedVanilla_1.0.1.jar Enhanced Vanilla Java Edition {enhanced_vanilla_remastered@Snapshot 19w49a DONE}
		mysticalworld-1.14.4-1.9.1.jar Mystical World {mysticalworld@1.14.4-1.9.1 DONE}
		mysticalwildlife-1.14.4-1.3.4.jar Mystical Wildlife {mysticalwildlife@1.3.4 DONE}
		forge-1.14.4-28.2.6-universal.jar Forge {forge@28.2.6 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
		Aquaculture-1.14.4-2.0.7.jar Aquaculture 2 {aquaculture@1.14.4-2.0.7 DONE}
		Charm-1.14.4-1.5.7.jar Charm {charm@1.14.4-1.5.7 DONE}
		More Dogs-1.0.3.jar More Dog Breeds {moredogs@1.0.3 DONE}
		mysticallib-1.14.4-1.16.1.jar Mystical Lib {mysticallib@1.14.4-1.16.1 DONE}
		Explorercraft-1.14.4-3.2.7.jar Explorercraft {explorercraft@3.2.7 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['SixtyMillionSqrd'/276, l='New World', x=-91.94, y=128.00, z=-17.90]]
	Data Packs: vanilla, mod:aquaculture, mod:arl, mod:autumnity, mod:betteranimalsplus, mod:charm, mod:citadel, mod:crocmod, mod:druidcraft, mod:eanimod, mod:enhanced_vanilla_remastered, mod:explorercraft, mod:forge, mod:goodnightsleep, mod:horse_colors, mod:jei, mod:lizardmod, mod:moredogs, mod:mysticallib, mod:mysticalwildlife, mod:mysticalworld, mod:pamhc2crops, mod:pamhc2foodcore, mod:pamhc2trees, mod:pandoras_creatures, mod:patchouli, mod:quark, mod:rats, mod:sea, mod:turtlemod, mod:upgrade_aquatic, mod:voyage, mod:waddles, mod:whisperwoods, mod:wildnature
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by SaemonMoki** [comment]
This should be fixed in the latest release. Please download our 0.5.3 version.

**Comment by sixtymillionsqrd** [comment]
Please reopen this. I am using the latest version of Genetic Animals for 1.14.4 and the issue still persists.

**Comment by SaemonMoki** [comment]
This was fixed.
